/* Guided course: existing ?step=1…9 routes remain available. */
const COURSE = [
 ['welcome','Начало','13:20–13:25',1],['metric','Что измеряем','13:25–13:40',1],
 ['excel-month','Календарный месяц','13:40–13:55',1],['excel-day','На календарный день','13:55–14:10',1],['excel-window','Скользящее окно','14:10–14:30',1],
 ['season','Сезонность','14:30–14:45',1],['waves','Наложение циклов','14:45–14:55',1],['forecast','Проверка прогноза','14:55–15:05',1],['distribution','Коварное среднее','15:05–15:15',1],['experiment','Достоверность вывода','15:15–15:35',1],
 ['assistant','Ассистент','15:45–15:55',2],['routing','Маршрутизация','15:55–16:10',2],['memo','Документ по регламенту','16:10–16:20',2],['rag-demo','Поиск по документам','16:20–16:30',2],
 ['mermaid','Визуализация','16:30–16:40',2],['agent-demo','Агент с инструментами','16:40–16:50',2],['process','Четыре линзы','16:50–17:05',2],['security','Контур обработки','17:05–17:20',2],['defense','Проект и презентация','17:20–17:45',2],['present','Доработка и защита','17:45–18:10',2]
];
const courseParams=new URLSearchParams(location.search), legacyMode=courseParams.has('step')&&!courseParams.has('section');
let section=courseParams.get('section')||'welcome';
const legacyRender=render;
function downloadText(name,text,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function courseHead(title,sub=''){const c=COURSE.find(x=>x[0]===section);return `<header class="stage-head"><div class="kicker">Занятие ${c?.[3]||2} · ${c?.[2]||''}</div><h2>${esc(title)}</h2><p>${esc(sub)}</p></header>`}
function field(id,label,value='',rows=3){return `<label>${esc(label)}<textarea id="${id}" rows="${rows}">${esc(value)}</textarea></label>`}
function courseGo(slug){section=slug;history.replaceState(null,'',location.pathname+'?section='+slug);render();window.scrollTo(0,document.querySelector('.course').offsetTop)}
function gate(){if(sessionStorage.getItem('tat-course-entered')==='yes')return false;el('stage').innerHTML=courseHead('Вход в учебный практикум','Введите пароль со слайда преподавателя.')+`<form id="entry" class="panel"><label>Учебный пароль<input id="entry-password" type="password" autocomplete="off" required></label><button class="button">Открыть практикум</button><p id="entry-error" role="status"></p><small>Здесь используются только обучающие примеры. Сведения ограниченного доступа не вводятся.</small></form>`;el('entry').onsubmit=e=>{e.preventDefault();if(el('entry-password').value.trim().toUpperCase()==='TATARSTAN13'){sessionStorage.setItem('tat-course-entered','yes');render()}else el('entry-error').textContent='Проверьте пароль на слайде преподавателя.'};return true}
render=function(){if(gate())return;if(legacyMode){legacyRender();return}let i=COURSE.findIndex(x=>x[0]===section);if(i<0){section='welcome';i=0}history.replaceState(null,'',location.pathname+'?section='+section);el('journey').innerHTML=COURSE.map((s,j)=>`<button data-section="${s[0]}" class="${j===i?'active':''}"><small>${s[2]}</small><span>${j+1}</span>${esc(s[1])}</button>`).join('');document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>courseGo(b.dataset.section));el('prev').disabled=i===0;el('next').disabled=i===COURSE.length-1;el('position').textContent=`${i+1} / ${COURSE.length}`;el('next-title').textContent=COURSE[i+1]?.[1]||'Практикум завершён';el('prev').onclick=()=>courseGo(COURSE[i-1][0]);el('next').onclick=()=>courseGo(COURSE[i+1][0]);state.step=COURSE[i][3]===1?0:5;
 if(section.startsWith('excel-'))return renderExcelCourse(section);
 if(['waves','forecast','distribution','experiment'].includes(section))return renderOriginalLab(section);
 if(section==='season'){state.step=2;renderSeason();return}
 if(section==='metric'){renderMetric();return}
 if(section==='security'){renderSecurity();const b=document.createElement('button');b.className='button secondary';b.id='security-save';b.textContent='Скачать результат для проекта';b.onclick=()=>{const raw=el('security-response').value;try{parseSecurityMarkdown(raw);downloadText('02-требования-безопасности.md',raw);sessionStorage.setItem('tat-security',raw)}catch(e){el('security-status').textContent=e.message}};el('stage').append(b);return}
 if(section==='defense')return renderDefense();
 if(typeof renderAssistantCourse==='function'&&['assistant','routing','memo','mermaid','process'].includes(section))return renderAssistantCourse(section);
 if(section==='welcome'){el('stage').innerHTML=courseHead('Работаем вместе с преподавателем','13 октября · Республика Татарстан · два практических занятия')+`<div class="panel"><h3>Подготовьте два окна</h3><ol><li>Этот практикум: данные, шаблоны запросов и визуальные результаты.</li><li><a href="https://gosprompt.ru/" target="_blank" rel="noopener">Госпромт</a>: вставка запроса и получение ответа.</li></ol><p>Первое занятие: 13:20–15:35. Перерыв: 15:35–15:45. Второе занятие: 15:45–18:10.</p><p>На шагах с запросами: заполните поля → скопируйте запрос → выполните его в Госпромте → перенесите ответ. На визуальных шагах меняйте параметры вместе с преподавателем.</p><p>Используйте только обучающие примеры. Названия организаций и должности условны. Личные и закрытые рабочие сведения сюда не загружаются.</p><a class="button" href="downloads/praktikum_obrashcheniya.xlsm">Скачать единую книгу Excel (.xlsm)</a></div>`;return}
 if(section==='present'){el('stage').innerHTML=courseHead('Доработайте и защитите проект','17:45–18:00 — доработка; 18:00–18:10 — две краткие защиты.')+`<div class="panel"><ol><li>Скачайте HTML-презентацию на предыдущем шаге.</li><li>Загрузите файл в Госпромт и попросите уточнить формулировки, сохранив структуру, навигацию и режим печати. Используйте только учебные сведения.</li><li>Откройте исправленный файл в браузере и проверьте листание и печать.</li><li>Защита: проблема и факт → выбранная технология → данные и контур → проверка качества → условия остановки.</li></ol><p>Один участник — до 3 минут; затем 2 минуты на вопросы. Если результат не подтверждён, отметьте, какие данные нужны.</p></div>`;return}
 const rag=section==='rag-demo';el('stage').innerHTML=courseHead(rag?'Демонстрация: ответ по документам':'Демонстрация: агент строит диаграмму',rag?'Преподаватель показывает поиск по источникам после упражнения с коротким регламентом.':'Преподаватель показывает вызов инструментов после упражнения Mermaid.')+`<div class="panel"><ol>${rag?'<li>Задать вопрос о норме трудового законодательства.</li><li>Проследить, какие фрагменты документов найдены.</li><li>Открыть первоисточник и проверить цитату, редакцию и вывод.</li><li>Задать вопрос, на который в базе нет ответа: система должна обозначить нехватку источников.</li>':'<li>Открыть учебную таблицу на большом числе строк.</li><li>Попросить построить динамику по месяцам с указанным знаменателем.</li><li>Показать вызов расчётного инструмента и сверить итог с контрольной таблицей.</li><li>Сопоставить с Mermaid: там визуализировались заданные числа, здесь инструмент рассчитывает их по данным.</li>'}</ol><p>Демонстрационный стенд открывает преподаватель. Доступ участников к нему не требуется.</p></div>`;
};
function renderOriginalLab(which){const names={waves:['Наложение циклов','harmonics.html','Добавляйте годовой и месячный циклы. Сравните сумму и наблюдения, затем откройте прогноз.'],forecast:['Прогноз на неизвестном периоде','index.html','Выберите модель до открытия будущего. Сравните ошибки на следующем периоде.'],distribution:['Среднее и распределение','distributions.html','Сопоставьте среднее, медиану и распределение. Проверьте влияние редких длительных случаев.'],experiment:['Срок эксперимента и доверительные интервалы','experiment.html','Задайте минимальный эффект и поток участников. Проследите накопление наблюдений и сужение интервалов. Не завершайте проверку при первом случайном различии.']};const [t,p,s]=names[which];el('stage').innerHTML=courseHead(t,s)+`<iframe class="source-lab" title="${esc(t)}" src="labs/${p}"></iframe><p><a href="labs/${p}" target="_blank" rel="noopener">Открыть визуализацию на весь экран</a></p>`;}
