'use strict';
const el=id=>document.getElementById(id),colors=['#00868c','#ff5533','#7060b5','#2274b8','#bb557a','#928128','#287453','#a15f37'];let data,model;
const fmt=(v,n=1)=>v.toLocaleString('ru-RU',{maximumFractionDigits:n});
function node(tag,attrs={},content){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(content!==undefined)e.textContent=content;return e}
function text(svg,x,y,s,size=15,fill='#69717e'){svg.append(node('text',{x,y,'font-size':size,fill,'font-family':'Arial'},s))}
function axes(svg,W,H,xlo,xhi,ylo,yhi,xticks,yticks){svg.replaceChildren();const x=v=>72+(v-xlo)/(xhi-xlo)*(W-106),y=v=>H-48-(v-ylo)/(yhi-ylo)*(H-85);for(const v of yticks){svg.append(node('line',{x1:72,x2:W-34,y1:y(v),y2:y(v),stroke:'#e1e4e5'}));text(svg,10,y(v)+5,fmt(v))}for(const v of xticks)text(svg,x(v)-8,H-22,fmt(v));return{x,y}}
function curve(id,key,H,hi){const svg=el(id),valid=model.results.filter(r=>r[key]!==null),a=axes(svg,580,H,1,8,0,hi,[1,2,3,4,5,6,7,8],key==='inertia'?[0,400,800,1200]:[0,.4,.8]);svg.append(node('polyline',{points:valid.map(r=>`${a.x(r.k)},${a.y(r[key])}`).join(' '),fill:'none',stroke:'#69717e','stroke-width':2}));for(const r of valid){const selected=r.k===Number(el('k').value);const c=node('circle',{cx:a.x(r.k),cy:a.y(r[key]),r:selected?7:4,fill:selected?'#ff5533':'#69717e'});c.append(node('title',{},`k=${r.k}: ${fmt(r[key],3)}`));svg.append(c)}text(svg,75,20,key==='inertia'?'WCSS · сумма квадратов расстояний':'Средний силуэт',16);text(svg,350,H-2,'Число кластеров k →',14)}
function draw(){const k=Number(el('k').value),r=model.results[k-1];el('kValue').textContent=k;const xs=data.points.map(p=>p[0]),ys=data.points.map(p=>p[1]);const loX=Math.floor((Math.min(...xs)-3)/5)*5,hiX=Math.ceil((Math.max(...xs)+3)/5)*5,loY=Math.max(0,Math.floor((Math.min(...ys)-15)/20)*20),hiY=Math.ceil((Math.max(...ys)+15)/20)*20;
const svg=el('scatter'),a=axes(svg,760,490,loX,hiX,loY,hiY,Array.from({length:Math.floor((hiX-loX)/10)+1},(_,i)=>loX+i*10),Array.from({length:Math.floor((hiY-loY)/80)+1},(_,i)=>loY+i*80));text(svg,74,20,'Доход, тыс. ₽ / месяц',16);text(svg,520,487,'Возраст, лет →',16);
data.points.forEach((p,i)=>{const c=node('circle',{cx:a.x(p[0]),cy:a.y(p[1]),r:3.1,fill:colors[r.labels[i]],opacity:.48,class:'observation'});c.append(node('title',{},`Участник ${i+1}: ${p[0]} лет, ${p[1]} тыс. ₽; кластер ${r.labels[i]+1}`));svg.append(c)});
r.originalCenters.forEach((p,j)=>{const g=node('g',{class:'centroid','data-cluster':j+1});for(const sign of [-1,1]){const attrs={x1:a.x(p[0])-10,x2:a.x(p[0])+10,y1:a.y(p[1])-sign*10,y2:a.y(p[1])+sign*10};g.append(node('line',{...attrs,stroke:'#fff','stroke-width':8}));g.append(node('line',{...attrs,stroke:colors[j],'stroke-width':4}))}g.append(node('title',{},`Центроид ${j+1}: ${fmt(p[0])} лет, ${fmt(p[1])} тыс. ₽`));svg.append(g)});
el('legend').replaceChildren();r.originalCenters.forEach((p,j)=>{const s=document.createElement('span');s.style.color=colors[j];s.textContent=`× ${j+1}: ${fmt(p[0])} лет · ${fmt(p[1])} тыс. ₽ · ${r.counts[j]} чел.`;el('legend').append(s)});
curve('elbow','inertia',290,model.results[0].inertia*1.05);curve('silplot','silhouette',220,1);el('wcss').textContent=fmt(r.inertia);el('silhouette').textContent=r.silhouette===null?'Не определён':fmt(r.silhouette,3);
const reduction=100*(1-model.results[1].inertia/model.results[0].inertia),best=model.results.slice(1).reduce((a,b)=>a.silhouette>b.silhouette?a:b).k;
el('explain').textContent=k===1?'Один центроид усредняет два облака и попадает между ними. Переместите бегунок на 2: центры окажутся внутри групп.':k===2?`Переход 1 → 2 уменьшил WCSS на ${fmt(reduction)}%. Здесь заметен локоть; максимальный силуэт среди k=2…8 — у k=${best}. Два кластера описывают два облака.`:`При k=${k} WCSS ниже, но мы уже дробим исходные облака. Самый высокий силуэт в проверенном диапазоне — у k=${best}; уменьшение ошибки само по себе не оправдывает дополнительные сегменты.`;
el('status').textContent=`${k} ${k===1?'кластер':k<5?'кластера':'кластеров'} · ${k} ${k===1?'центроид':k<5?'центроида':'центроидов'} · ${data.points.length} точек остаются на своих местах.`;window.clusterState={k,...r,results:model.results,points:data.points};}
fetch('clusters-data.json').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(d=>{data=d;model=Clusters.calculate(data.points);el('k').disabled=false;el('k').oninput=draw;draw()}).catch(e=>el('status').textContent='Не удалось загрузить или рассчитать данные: '+e.message);
function hash(){if(location.hash==='#method')el('method').open=true}window.addEventListener('hashchange',hash);hash();
