(()=>{'use strict';const M=DistributionModel,$=id=>document.getElementById(id),W=900,H=400,P={l:74,r:28,t:28,b:62},PW=W-P.l-P.r,PH=H-P.t-P.b;
let values=M.preset('normal'),history=[],drag=null,histMax=20,active='normal',grouped=false,frame=0;
const colors={mean:'#e34b2d',median:'#00868c',p90:'#2274b8'},number=v=>v===null?'—':v.toLocaleString('ru-RU',{maximumFractionDigits:2});
function save(){history.push({values:[...values],grouped,active});if(history.length>30)history.shift();}
function stateMessage(text){$('status').textContent=text;}
function fieldValues(){const i=M.clamp(Math.round(Number($('pointIndex').value)||1)-1,0,Math.max(0,values.length-1));$('pointIndex').value=i+1;$('pointValue').value=values.length?Math.round(values[i]*100)/100:0;const j=M.clamp(Math.round(Number($('binIndex').value)||1)-1,0,39);$('binCount').value=M.histogram(values)[j];$('binRange').textContent=`Интервал ${j+1}: ${number(j*M.WIDTH)}–${number((j+1)*M.WIDTH)} минуты${j===39?' (включая 100)':''}`;}
function context(canvas){const dpr=window.devicePixelRatio||1;if(canvas.width!==W*dpr){canvas.width=W*dpr;canvas.height=H*dpr;}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,W,H);c.font='20px Arial';return c;}
function line(c,x1,y1,x2,y2,color,width=2,dash=[]){c.beginPath();c.strokeStyle=color;c.lineWidth=width;c.setLineDash(dash);c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();c.setLineDash([]);}
function axes(c,ymax,mode){c.fillStyle='#646c76';c.textAlign='right';for(let i=0;i<=4;i++){const y=P.t+PH-i/4*PH;line(c,P.l,y,W-P.r,y,'#e3e6e8',1);c.fillText(number(i/4*ymax),P.l-12,y+7);}c.textAlign='center';for(let i=0;i<=4;i++){const x=P.l+i/4*PW;const val=mode==='hist'?i*25:values.length?Math.round(1+i/4*(values.length-1)):i*40;c.fillText(String(val),x,H-P.b+29);}c.textAlign='left';c.font='18px Arial';c.fillText(mode==='hist'?'Число наблюдений':'Минуты',P.l,19);c.textAlign='right';c.fillText(mode==='hist'?'Значение, минут':'Порядок наблюдений',W-P.r,H-10);}
function plotSeries(stats){const c=context($('series'));axes(c,100,'series');if(values.length){c.save();c.beginPath();c.rect(P.l,P.t,PW,PH);c.clip();c.beginPath();values.forEach((v,i)=>{const x=P.l+(values.length===1?.5:i/(values.length-1))*PW,y=P.t+PH*(1-v/100);i?c.lineTo(x,y):c.moveTo(x,y);});c.strokeStyle='#89969c';c.lineWidth=2;c.stroke();if(values.length===1){c.beginPath();c.arc(P.l+PW/2,P.t+PH*(1-values[0]/100),4,0,Math.PI*2);c.fillStyle='#89969c';c.fill();}for(const [key,dash] of [['mean',[]],['median',[10,5]],['p90',[3,5]]]){const y=P.t+PH*(1-stats[key]/100);line(c,P.l,y,W-P.r,y,colors[key],3,dash);}c.restore();}}
function plotHistogram(stats,counts){const c=context($('histogram'));axes(c,histMax,'hist');c.fillStyle='#d5e7e5';counts.forEach((v,i)=>{const h=v/histMax*PH;c.fillRect(P.l+i/40*PW+1,P.t+PH-h,PW/40-2,h);});if(stats.n)for(const [key,dash] of [['mean',[]],['median',[10,5]],['p90',[3,5]]]){const x=P.l+stats[key]/100*PW;line(c,x,P.t,x,H-P.b,colors[key],3,dash);}}
function render(){frame=0;const counts=M.histogram(values),stats=M.statistics(values);if(!drag||drag.kind!=='hist')histMax=Math.max(10,Math.ceil(Math.max(...counts)*1.25/5)*5);for(const k of ['mean','median','p90'])$(k).textContent=stats[k]===null?'—':number(stats[k])+' мин';$('n').textContent=stats.n.toLocaleString('ru-RU')+' наблюдений';$('pointIndex').max=Math.max(1,stats.n);$('undo').disabled=!history.length;$('download').disabled=!stats.n;document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===active)));plotSeries(stats);plotHistogram(stats,counts);window.distributionState={values:[...values],counts,stats,grouped,histMax};}
function update(){if(!frame)frame=requestAnimationFrame(render);}
function coordinate(e,canvas,kind){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H;return {inside:x>=P.l&&x<=W-P.r&&y>=P.t&&y<=H-P.b,i:kind==='series'?M.clamp(Math.round((x-P.l)/PW*(values.length-1)),0,values.length-1):M.clamp(Math.floor((x-P.l)/PW*40),0,39),v:M.clamp((1-(y-P.t)/PH)*(kind==='series'?100:histMax),0,kind==='series'?100:histMax)};}
function paint(point){if(drag.kind==='series'){M.stroke(values,drag.last,point);values=values.map(v=>Math.round(v*100)/100);grouped=false;}else{const next=[...drag.counts];M.stroke(next,drag.last,point,0,2000);const rounded=next.map(v=>Math.round(v));if(rounded.reduce((a,b)=>a+b,0)>2000){stateMessage('Для рисования доступно до 2000 наблюдений. Уменьшите высоту столбиков.');return;}drag.counts=rounded;values=M.fromHistogram(drag.counts);grouped=true;}drag.last=point;active='';update();}
for(const [id,kind] of [['series','series'],['histogram','hist']]){const canvas=$(id);canvas.addEventListener('pointerdown',e=>{if(e.button!==0||drag)return;const hit=coordinate(e,canvas,kind);if(!hit.inside)return;e.preventDefault();save();if(kind==='series'&&!values.length)values=Array(160).fill(0);const point=coordinate(e,canvas,kind);drag={kind,id:e.pointerId,last:point,counts:M.histogram(values)};canvas.setPointerCapture(e.pointerId);paint(point);});canvas.addEventListener('pointermove',e=>{if(!drag||drag.kind!==kind||drag.id!==e.pointerId)return;e.preventDefault();paint(coordinate(e,canvas,kind));});const finish=(e,cancel)=>{if(!drag||drag.kind!==kind||drag.id!==e.pointerId)return;if(cancel){const previous=history.pop();values=previous.values;grouped=previous.grouped;active=previous.active;}drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);render();fieldValues();stateMessage(cancel?'Жест отменён.':grouped?'Гистограмма изменена. Ряд восстановлен по серединам интервалов; порядок условный.':'Ряд изменён. Гистограмма и показатели пересчитаны.');};canvas.addEventListener('pointerup',e=>finish(e,false));canvas.addEventListener('pointercancel',e=>finish(e,true));}
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{save();active=b.dataset.preset;values=M.preset(active);grouped=false;render();fieldValues();stateMessage('Заготовка: '+b.textContent+'. Рисуйте на любом из графиков.');}));$('undo').addEventListener('click',()=>{const p=history.pop();if(!p)return;values=p.values;grouped=p.grouped;active=p.active;render();fieldValues();stateMessage('Предыдущее изменение отменено.');});$('clear').addEventListener('click',()=>{save();values=[];active='';grouped=false;render();fieldValues();stateMessage('Пустой набор. Начните рисовать или выберите заготовку.');});
$('pointIndex').addEventListener('change',fieldValues);$('binIndex').addEventListener('change',fieldValues);
$('applyPoint').addEventListener('click',()=>{const index=Number($('pointIndex').value),v=Number($('pointValue').value);if(!Number.isInteger(index)||index<1||index>Math.max(1,values.length)||!Number.isFinite(v)||v<0||v>100){stateMessage('Укажите существующий номер наблюдения и значение от 0 до 100.');return;}save();if(!values.length)values=[v];else values[index-1]=v;active='';grouped=false;render();fieldValues();stateMessage('Значение изменено.');});
$('applyBin').addEventListener('click',()=>{const index=Number($('binIndex').value),v=Number($('binCount').value);if(!Number.isInteger(index)||index<1||index>40||!Number.isInteger(v)||v<0||v>2000){stateMessage('Укажите интервал 1–40 и целое число наблюдений 0–2000.');return;}const counts=M.histogram(values);counts[index-1]=v;if(counts.reduce((a,b)=>a+b,0)>2000){stateMessage('Допустимо не более 2000 наблюдений во всём наборе.');return;}save();values=M.fromHistogram(counts);active='';grouped=true;render();fieldValues();stateMessage('Частота изменена. Порядок восстановленного ряда условный.');});
$('download').addEventListener('click',()=>{const csv='observation,minutes\n'+values.map((v,i)=>`${i+1},${v}`).join('\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='distribution-observations.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
function openMethod(){if(location.hash==='#method')$('method').open=true;}addEventListener('hashchange',openMethod);openMethod();render();fieldValues();stateMessage('Выберите заготовку или рисуйте с нажатой кнопкой мыши.');
})();
